ALTER TABLE leads ADD COLUMN IF NOT EXISTS priority SMALLINT NOT NULL DEFAULT 2 CHECK (priority BETWEEN 1 AND 3);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS next_action VARCHAR(180);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS next_action_at TIMESTAMPTZ;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS lost_reason VARCHAR(180);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS leads_next_action_idx ON leads (next_action_at, priority, status);
