// Real-brand vehicles with real photo assets
// Kept Silhouette exports as fallback (used only if img fails)

function SilhouetteSports({ color = "#0a0a0a", accent = "#c8a24b" }) {
  return (
    <svg viewBox="0 0 800 300" xmlns="http://www.w3.org/2000/svg">
      <path d="M 80 210 C 90 180, 110 165, 150 160 L 250 155 C 280 130, 320 115, 380 108 L 480 105 C 540 108, 590 125, 630 155 L 720 165 C 750 170, 765 185, 770 210 L 770 220 L 720 225 C 715 245, 700 258, 675 258 C 650 258, 635 245, 630 225 L 210 225 C 205 245, 190 258, 165 258 C 140 258, 125 245, 120 225 L 80 220 Z"
        fill={color} opacity="0.92"/>
      <circle cx="165" cy="235" r="22" fill={color}/>
      <circle cx="675" cy="235" r="22" fill={color}/>
    </svg>
  );
}
function SilhouetteSuv(p) { return <SilhouetteSports {...p}/>; }
function SilhouetteSedan(p) { return <SilhouetteSports {...p}/>; }
function Silhouette(p) { return <SilhouetteSports {...p}/>; }

// Real vehicle catalog with photo assets
const VEHICLES = [
  {
    id: "porsche-911-gt3",
    brand: "Porsche",
    model: "911 GT3",
    name: { es: "Porsche 911 GT3", en: "Porsche 911 GT3" },
    year: 2026,
    type: "sports",
    kind: "new",
    price: 189500,
    priceLabel: { es: "USD", en: "USD" },
    tagline: { es: "Purista. Analógico. Definitivo.", en: "Purist. Analog. Definitive." },
    image: "assets/porsche-911-gt3.jpg",
    images: ["assets/porsche-911-gt3.jpg", "assets/porsche-911-gt3-alt.jpg", "assets/porsche-911-three-quarter.jpg", "assets/porsche-interior.jpg"],
    color: "#e5e2d8",
    colors: [
      { name: { es: "Chalk", en: "Chalk" }, hex: "#e5e2d8" },
      { name: { es: "Negro Volcánico", en: "Volcanic Black" }, hex: "#0a0a0a" },
      { name: { es: "Gris Ágata", en: "Agate Grey" }, hex: "#5a5852" },
      { name: { es: "Champagne", en: "Champagne" }, hex: "#c8a24b" },
      { name: { es: "Rojo Guardia", en: "Guards Red" }, hex: "#a63325" },
    ],
    specs: {
      engine: "4.0L H6 Naturally Aspirated",
      power: "502 hp @ 8,400 rpm",
      torque: "470 Nm @ 6,100 rpm",
      accel: "3.2s",
      topspeed: "318 km/h",
      transmission: "7-Speed PDK",
      drive: "RWD",
      year: "2026",
      kms: "0 km",
    },
    location: {
      dealer: "Porsche Center Polanco",
      address: "Av. Presidente Masaryk 407\nMiguel Hidalgo, CDMX 11560",
      distance: "3.2 km",
      phone: "+52 55 5281 4567",
      lat: 19.4324, lng: -99.1935,
    },
    stock: 2,
    views: 847,
  },
  {
    id: "porsche-cayenne-turbo-gt",
    brand: "Porsche",
    model: "Cayenne Turbo GT",
    name: { es: "Porsche Cayenne Turbo GT", en: "Porsche Cayenne Turbo GT" },
    year: 2026,
    type: "suv",
    kind: "new",
    price: 195700,
    priceLabel: { es: "USD", en: "USD" },
    tagline: { es: "Fuerza sin compromiso.", en: "Force without compromise." },
    image: "assets/cayenne-turbo-gt.jpg",
    images: ["assets/cayenne-turbo-gt.jpg", "assets/cayenne-turbo-gt-2.jpg"],
    color: "#1a1917",
    colors: [
      { name: { es: "Blanco Carrara", en: "Carrara White" }, hex: "#f0eee8" },
      { name: { es: "Negro Volcánico", en: "Volcanic Black" }, hex: "#1a1917" },
      { name: { es: "Azul Gentiana", en: "Gentian Blue" }, hex: "#1e3a5f" },
      { name: { es: "Rojo Guardia", en: "Guards Red" }, hex: "#a63325" },
    ],
    specs: {
      engine: "4.0L V8 Twin-Turbo",
      power: "631 hp @ 6,500 rpm",
      torque: "850 Nm @ 2,300 rpm",
      accel: "3.3s",
      topspeed: "300 km/h",
      transmission: "8-Speed Tiptronic S",
      drive: "AWD",
      year: "2026",
      kms: "0 km",
    },
    location: {
      dealer: "Porsche Center Polanco",
      address: "Av. Presidente Masaryk 407\nMiguel Hidalgo, CDMX 11560",
      distance: "3.2 km",
      phone: "+52 55 5281 4567",
      lat: 19.4324, lng: -99.1935,
    },
    stock: 1,
    views: 623,
  },
  {
    id: "porsche-taycan-turbo-s",
    brand: "Porsche",
    model: "Taycan Turbo S",
    name: { es: "Porsche Taycan Turbo S", en: "Porsche Taycan Turbo S" },
    year: 2025,
    type: "sedan",
    kind: "used",
    price: 129900,
    priceLabel: { es: "USD", en: "USD" },
    tagline: { es: "Eléctrico. Certificado.", en: "Electric. Certified." },
    image: "assets/taycan-turbo-s.jpg",
    images: ["assets/taycan-turbo-s.jpg", "assets/taycan-turbo-s-2.jpg"],
    color: "#0a0a0a",
    colors: [
      { name: { es: "Negro Volcánico", en: "Volcanic Black" }, hex: "#0a0a0a" },
      { name: { es: "Blanco Carrara", en: "Carrara White" }, hex: "#f0eee8" },
      { name: { es: "Frozen Blue", en: "Frozen Blue" }, hex: "#3a5a7a" },
    ],
    specs: {
      engine: "Dual PSM Electric",
      power: "751 hp (Launch Control)",
      torque: "1,050 Nm",
      accel: "2.6s",
      topspeed: "260 km/h",
      transmission: "2-Speed AT",
      drive: "AWD",
      year: "2025",
      kms: "12,450 km",
    },
    location: {
      dealer: "Porsche Center Santa Fe",
      address: "Av. Vasco de Quiroga 3800\nCuajimalpa, CDMX 05348",
      distance: "18.7 km",
      phone: "+52 55 5292 8100",
      lat: 19.3630, lng: -99.2650,
    },
    stock: 1,
    views: 1102,
  },
  {
    id: "bmw-m4-competition",
    brand: "BMW",
    model: "M4 Competition xDrive",
    name: { es: "BMW M4 Competition xDrive", en: "BMW M4 Competition xDrive" },
    year: 2024,
    type: "sports",
    kind: "used",
    price: 84500,
    priceLabel: { es: "USD", en: "USD" },
    tagline: { es: "Precisión bávara.", en: "Bavarian precision." },
    image: "assets/bmw-m4.jpg",
    images: ["assets/bmw-m4.jpg", "assets/bmw-m4-2.jpg"],
    color: "#1e3a5f",
    colors: [
      { name: { es: "Isle of Man Green", en: "Isle of Man Green" }, hex: "#2d4a3a" },
      { name: { es: "Alpine White", en: "Alpine White" }, hex: "#f0eee8" },
      { name: { es: "Sao Paulo Yellow", en: "Sao Paulo Yellow" }, hex: "#d4a52a" },
      { name: { es: "Portimao Blue", en: "Portimao Blue" }, hex: "#1e3a5f" },
    ],
    specs: {
      engine: "3.0L I6 Twin-Turbo",
      power: "503 hp",
      torque: "650 Nm",
      accel: "3.5s",
      topspeed: "290 km/h",
      transmission: "8-Speed M Steptronic",
      drive: "AWD (xDrive)",
      year: "2024",
      kms: "8,900 km",
    },
    location: {
      dealer: "BMW Interlomas",
      address: "Blvd. Manuel Ávila Camacho 2610\nHuixquilucan, EdoMex 52786",
      distance: "22.4 km",
      phone: "+52 55 5290 0234",
      lat: 19.3945, lng: -99.2841,
    },
    stock: 1,
    views: 456,
  },
  {
    id: "mercedes-amg-gt",
    brand: "Mercedes-AMG",
    model: "GT 63 Coupé",
    name: { es: "Mercedes-AMG GT 63", en: "Mercedes-AMG GT 63" },
    year: 2025,
    type: "sports",
    kind: "new",
    price: 176800,
    priceLabel: { es: "USD", en: "USD" },
    tagline: { es: "Handcrafted en Affalterbach.", en: "Handcrafted in Affalterbach." },
    image: "assets/amg-gt.jpg",
    images: ["assets/amg-gt.jpg", "assets/amg-gt-2.jpg"],
    color: "#f0eee8",
    colors: [
      { name: { es: "Blanco Diamond", en: "Diamond White" }, hex: "#f0eee8" },
      { name: { es: "Obsidian Black", en: "Obsidian Black" }, hex: "#0a0a0a" },
      { name: { es: "Selenite Grey", en: "Selenite Grey" }, hex: "#6b6660" },
    ],
    specs: {
      engine: "4.0L V8 Biturbo",
      power: "577 hp",
      torque: "800 Nm",
      accel: "3.2s",
      topspeed: "315 km/h",
      transmission: "9-Speed AMG SPEEDSHIFT",
      drive: "AWD (4MATIC+)",
      year: "2025",
      kms: "0 km",
    },
    location: {
      dealer: "Mercedes-Benz Polanco",
      address: "Ejército Nacional 843-B\nMiguel Hidalgo, CDMX 11540",
      distance: "5.1 km",
      phone: "+52 55 5203 1200",
      lat: 19.4383, lng: -99.2010,
    },
    stock: 3,
    views: 712,
  },
  {
    id: "audi-rs-etron-gt",
    brand: "Audi",
    model: "RS e-tron GT",
    name: { es: "Audi RS e-tron GT", en: "Audi RS e-tron GT" },
    year: 2025,
    type: "sedan",
    kind: "new",
    price: 148900,
    priceLabel: { es: "USD", en: "USD" },
    tagline: { es: "Eléctrico. Deportivo. Vorsprung.", en: "Electric. Sporting. Vorsprung." },
    image: "assets/audi-etron-gt.jpg",
    images: ["assets/audi-etron-gt.jpg"],
    color: "#5a5852",
    colors: [
      { name: { es: "Tactical Green", en: "Tactical Green" }, hex: "#3a4a3d" },
      { name: { es: "Daytona Grey", en: "Daytona Grey" }, hex: "#5a5852" },
      { name: { es: "Suzuka Grey", en: "Suzuka Grey" }, hex: "#a8a29a" },
    ],
    specs: {
      engine: "Dual Motor EV (93 kWh)",
      power: "637 hp (Boost)",
      torque: "830 Nm",
      accel: "3.3s",
      topspeed: "250 km/h",
      transmission: "2-Speed AT",
      drive: "AWD (quattro)",
      year: "2025",
      kms: "0 km",
    },
    location: {
      dealer: "Audi Santa Fe",
      address: "Prol. Paseo de la Reforma 400\nSanta Fe, CDMX 05348",
      distance: "17.9 km",
      phone: "+52 55 5292 4500",
      lat: 19.3620, lng: -99.2740,
    },
    stock: 2,
    views: 534,
  },
  {
    id: "porsche-macan-gts",
    brand: "Porsche",
    model: "Macan GTS",
    name: { es: "Porsche Macan GTS", en: "Porsche Macan GTS" },
    year: 2026,
    type: "suv",
    kind: "new",
    price: 89400,
    priceLabel: { es: "USD", en: "USD" },
    tagline: { es: "Compacto. Sin límites.", en: "Compact. Limitless." },
    image: "assets/macan-gts.jpg",
    images: ["assets/macan-gts.jpg"],
    color: "#a63325",
    colors: [
      { name: { es: "Rojo Guardia", en: "Guards Red" }, hex: "#a63325" },
      { name: { es: "Negro Volcánico", en: "Volcanic Black" }, hex: "#1a1917" },
      { name: { es: "Blanco Carrara", en: "Carrara White" }, hex: "#f0eee8" },
    ],
    specs: {
      engine: "2.9L V6 Twin-Turbo",
      power: "434 hp",
      torque: "550 Nm",
      accel: "4.5s",
      topspeed: "272 km/h",
      transmission: "7-Speed PDK",
      drive: "AWD",
      year: "2026",
      kms: "0 km",
    },
    location: {
      dealer: "Porsche Center Santa Fe",
      address: "Av. Vasco de Quiroga 3800\nCuajimalpa, CDMX 05348",
      distance: "18.7 km",
      phone: "+52 55 5292 8100",
      lat: 19.3630, lng: -99.2650,
    },
    stock: 4,
    views: 892,
  },
  {
    id: "porsche-panamera-4s",
    brand: "Porsche",
    model: "Panamera 4S",
    name: { es: "Porsche Panamera 4S", en: "Porsche Panamera 4S" },
    year: 2024,
    type: "sedan",
    kind: "used",
    price: 98500,
    priceLabel: { es: "USD", en: "USD" },
    tagline: { es: "Gran turismo. Certificado.", en: "Grand tourer. Certified." },
    image: "assets/panamera.jpg",
    images: ["assets/panamera.jpg"],
    color: "#0a0a0a",
    colors: [
      { name: { es: "Negro Volcánico", en: "Volcanic Black" }, hex: "#0a0a0a" },
      { name: { es: "Gris Ágata", en: "Agate Grey" }, hex: "#5a5852" },
    ],
    specs: {
      engine: "2.9L V6 Twin-Turbo",
      power: "443 hp",
      torque: "550 Nm",
      accel: "4.1s",
      topspeed: "295 km/h",
      transmission: "8-Speed PDK",
      drive: "AWD",
      year: "2024",
      kms: "24,800 km",
    },
    location: {
      dealer: "Porsche Center Polanco",
      address: "Av. Presidente Masaryk 407\nMiguel Hidalgo, CDMX 11560",
      distance: "3.2 km",
      phone: "+52 55 5281 4567",
      lat: 19.4324, lng: -99.1935,
    },
    stock: 1,
    views: 378,
  },
];

// Customer reviews
const REVIEWS = [
  {
    id: 1,
    name: "Ricardo Alcántara",
    role: { es: "Empresario · CDMX", en: "Entrepreneur · Mexico City" },
    avatar: "assets/reviewer-1.jpg",
    rating: 5,
    date: "2026-07-12",
    vehicle: "Porsche 911 GT3",
    text: {
      es: "El proceso completamente digital me dejó sin palabras. Agendé test drive un martes, hicimos oferta el jueves, y el sábado ya tenía las llaves. Transparente, sin fricciones. El asesor Camila fue impecable.",
      en: "The fully digital process left me speechless. Booked test drive Tuesday, made offer Thursday, keys in hand Saturday. Transparent, frictionless. Advisor Camila was flawless.",
    },
  },
  {
    id: 2,
    name: "María Fernanda Ruiz",
    role: { es: "Arquitecta · Monterrey", en: "Architect · Monterrey" },
    avatar: "assets/reviewer-2.jpg",
    rating: 5,
    date: "2026-06-28",
    vehicle: "Audi RS e-tron GT",
    text: {
      es: "Compré un e-tron desde otra ciudad. El visor 360°, la ficha técnica completa y la video-llamada con el vendedor hicieron que confiara antes de viajar a verlo. Llegó exactamente como lo prometieron.",
      en: "Bought an e-tron from another city. The 360° viewer, complete spec sheet, and video call with the seller made me trust before flying to see it. Arrived exactly as promised.",
    },
  },
  {
    id: 3,
    name: "Andrés Villaseñor",
    role: { es: "Coleccionista · Guadalajara", en: "Collector · Guadalajara" },
    avatar: "assets/reviewer-3.jpg",
    rating: 5,
    date: "2026-05-15",
    vehicle: "Mercedes-AMG GT 63",
    text: {
      es: "He comprado 4 autos aquí en 2 años. La curaduría de inventario, los precios justos y el sistema de ofertas transparente lo convierten en mi único destino. Cada auto llega certificado punto por punto.",
      en: "Bought 4 cars here in 2 years. Curated inventory, fair pricing, and transparent offer system make it my only destination. Every car arrives point-by-point certified.",
    },
  },
];

Object.assign(window, { VEHICLES, REVIEWS, Silhouette, SilhouetteSports, SilhouetteSuv, SilhouetteSedan });
