// Copy for the public platform landing, in the two languages the showroom ships with.
// Headlines are split into lines so each one can be revealed on its own; `em` marks
// the line that carries the gold accent.
export const LANDING_LANGUAGES = ["es", "en"];

export const LANDING_COPY = {
  es: {
    label: "Español",
    nav: { experience: "La experiencia", platform: "La plataforma", how: "Cómo funciona", demo: "Ver demo", login: "Iniciar sesión", cta: "Crear showroom" },
    hero: {
      kicker: "Software para concesionarios que quieren vender con contexto",
      lines: [{ t: "Tu inventario" }, { t: "vende antes", em: true }, { t: "de hablar." }],
      body: "Stock, leads, citas y cotizaciones en una sola experiencia. Tu equipo sabe qué vio cada cliente y cuál es el siguiente paso.",
      primary: "Crear mi showroom",
      secondary: "Explorar una demo",
      metaLeft: "ZEVROA / 2026",
      metaRight: "Inventario · clientes · citas",
      objectLabel: "Objeto 3D editorial de ZEVROA",
    },
    proof: {
      kicker: "La plataforma",
      lines: [{ t: "Stock, leads," }, { t: "citas y showroom." }, { t: "Todo conectado." }],
      body: "Publica cada vehículo una vez, responde con el contexto correcto y convierte la intención en una próxima acción.",
      action: "Ver la plataforma en acción",
      overlayTag: "01 / OPERACIÓN",
      overlayLines: [{ t: "Una pantalla" }, { t: "para avanzar.", em: true }],
      overlayMeta: "Inventario · CRM · citas · cotizaciones",
      imageAlt: "Panel de ZEVROA con el inventario del concesionario",
    },
    platform: {
      kicker: "Lo que antes estaba separado",
      lines: [{ t: "Una operación" }, { t: "que se mueve" }, { t: "como una sola." }],
      body: "ZEVROA une la vitrina que ve tu cliente con las herramientas que usa tu equipo para vender.",
      action: "Conocer el flujo completo",
      items: [
        { index: "01", title: "Inventario", body: "Fichas, fotos, videos y 3D listos para publicar." },
        { index: "02", title: "Clientes", body: "Cada lead llega con vehículo, canal y próxima acción." },
        { index: "03", title: "Citas", body: "Agenda y confirma visitas sin perder el hilo." },
        { index: "04", title: "Cotizaciones", body: "Comparte una propuesta clara y recibe la decisión." },
      ],
    },
    chapters: [
      {
        kicker: "01 · Publica",
        lines: [{ t: "Tu inventario," }, { t: "presentado" }, { t: "como merece." }],
        body: "Cada vehículo sale con ficha completa, fotos ordenadas y una vista previa que apruebas antes de que el cliente lo vea.",
        mediaAlt: "Vehículo publicado en un showroom ZEVROA",
        card: { tag: "Inventario", status: "Publicado", title: "Porsche Taycan Turbo S", meta: "Ficha completa · showroom listo" },
      },
      {
        kicker: "02 · Responde",
        lines: [{ t: "Cada conversación" }, { t: "llega con" }, { t: "su contexto." }],
        body: "Sabes qué vehículo miró, qué preguntó y quién lo atiende. El equipo responde sin reconstruir la historia cada vez.",
        steps: [
          { index: "01 · Señal", title: "El cliente deja pistas.", body: "Visita una ficha, guarda un modelo, pide una cotización. Todo queda registrado." },
          { index: "02 · Lead", title: "María quiere verlo.", quote: "“¿Puedo agendar una visita esta semana?”", meta: "Porsche Taycan Turbo S · hace 4 min" },
          { index: "03 · Respuesta", title: "El equipo contesta con todo a la mano.", body: "Historial, vehículo y próxima acción en la misma pantalla." },
        ],
      },
      {
        kicker: "03 · Cierra",
        lines: [{ t: "De la intención" }, { t: "a la cita firmada." }],
        body: "Agenda, cotiza y da seguimiento hasta que el cliente decide. Sin hojas sueltas ni conversaciones perdidas.",
        action: "Abrir showroom de ejemplo",
        appointment: { tag: "Cita confirmada", status: "Hoy", time: "4:30 PM", meta: "Visita al showroom · Porsche Cayenne Turbo GT" },
        list: [
          { title: "Agenda", body: "El cliente elige hora y tu equipo la confirma en un toque." },
          { title: "Cotiza", body: "Genera una propuesta con precio, plan y condiciones listas para compartir." },
          { title: "Sigue", body: "Cada oportunidad avanza con recordatorios hasta el cierre." },
        ],
      },
    ],
    pains: {
      kicker: "El día a día",
      heading: "¿Te suena esto?",
      body: "No es falta de ganas. Es que el inventario, los mensajes y la agenda viven en sitios distintos.",
      items: [
        { before: "Publicas el mismo carro cinco veces", after: "Lo cargas una vez y sale en tu showroom, en la ficha y en el flyer." },
        { before: "Persigues un cliente por WhatsApp sin saber qué miró", after: "El lead llega con el vehículo, el canal y la conversación anterior." },
        { before: "Anotas las visitas en una libreta o en el chat", after: "El cliente elige hora y la cita queda confirmada en la agenda." },
        { before: "Haces la cotización a mano cada vez", after: "Generas la propuesta con precio y condiciones y la compartes por enlace." },
      ],
    },
    compare: {
      kicker: "La diferencia",
      heading: "Lo mismo, con y sin ZEVROA.",
      manual: "A mano",
      withUs: "Con ZEVROA",
      rows: [
        { label: "Publicar un vehículo", manual: "Fotos por WhatsApp, texto repetido en cada portal", withUs: "Una ficha que alimenta showroom, cartel y redes" },
        { label: "Responder un lead", manual: "Preguntar de nuevo qué vehículo le interesaba", withUs: "Historial y vehículo en la misma pantalla" },
        { label: "Agendar una visita", manual: "Ida y vuelta de mensajes hasta cuadrar la hora", withUs: "El cliente reserva sobre tu horario real" },
        { label: "Saber qué se movió", manual: "Memoria y una hoja de cálculo", withUs: "Reportes de inventario, leads y cierres" },
        { label: "Tener web propia", manual: "Presupuesto, diseñador y meses", withUs: "Showroom en línea la misma tarde" },
      ],
    },
    demo: {
      kicker: "Hablar con alguien",
      heading: "¿Prefieres que te lo enseñemos?",
      body: "Déjanos tus datos y te escribimos en menos de un día laborable para agendar una demo sobre tu propio inventario.",
      fields: { name: "Tu nombre", email: "Correo electrónico", phone: "Teléfono o WhatsApp", dealership: "Nombre del concesionario", size: "¿Cuántos vehículos manejas?" },
      sizes: ["Menos de 20", "20 a 50", "50 a 150", "Más de 150"],
      consent: "Acepto que ZEVROA use estos datos para contactarme sobre la demo.",
      submit: "Solicitar demo",
      sending: "Enviando…",
      success: "Recibido. Te escribimos en menos de un día laborable.",
      error: "No se pudo enviar. Inténtalo otra vez o escríbenos por otro canal.",
      alt: "¿Prefieres probarlo tú? Crea tu showroom y mira el panel por dentro.",
    },
    voices: { kicker: "Concesionarios", heading: "Lo que dicen quienes ya lo usan." },
    integrations: {
      kicker: "Conexiones",
      heading: "Conectado con lo que ya usas.",
      body: "Nada de migrar tu forma de trabajar. ZEVROA se enchufa a las herramientas con las que ya vendes.",
      items: [
        { name: "WhatsApp", detail: "Comparte fichas y responde leads por el canal que tus clientes ya usan." },
        { name: "Google Calendar", detail: "Las citas confirmadas se sincronizan con el calendario del equipo." },
        { name: "Instagram y Facebook", detail: "Genera la publicacion de cada vehiculo lista para subir." },
        { name: "Stripe", detail: "Cobra la suscripcion con checkout y facturacion automatica." },
        { name: "Correo", detail: "Avisos de leads, citas y cotizaciones al buzon de tu equipo." },
        { name: "Excel", detail: "Sube tu inventario completo de una vez desde una hoja de calculo." },
        { name: "Tu dominio", detail: "Conecta tu propia direccion web cuando quieras, o usa la incluida." },
        { name: "Google y buscadores", detail: "Cada ficha sale con su SEO, sitemap y datos estructurados." },
      ],
    },
    pricing: {
      kicker: "Planes",
      heading: "Sabes lo que pagas antes de escribirnos.",
      body: "Sin instalación, sin permanencia y con 14 días de prueba. Cambias de plan desde el panel cuando tu inventario crezca.",
      note: "Precios en USD por mes, impuestos aparte. Todos los planes incluyen showroom, inventario, clientes y agenda de citas.",
      cta: "Empezar la prueba",
      perMonth: "/ mes",
      plans: [
        { code: "starter", name: "Starter", price: "99", limit: "Hasta 40 vehículos", body: "Para un concesionario que abre su vitrina digital.", features: ["Showroom con tu marca", "Inventario y clientes", "Agenda de citas"] },
        { code: "growth", name: "Growth", price: "249", limit: "Hasta 150 vehículos", featured: true, body: "Para un equipo comercial que ya vive de los leads.", features: ["Todo lo de Starter", "Publicaciones para redes", "Cotizaciones y reportes"] },
        { code: "scale", name: "Scale", price: "499", limit: "Inventario ilimitado", body: "Para operaciones con varias sucursales y usuarios.", features: ["Todo lo de Growth", "Vehículos sin límite", "Soporte prioritario"] },
      ],
    },
    faq: {
      kicker: "Antes de empezar",
      heading: "Las dudas que nos hacen siempre.",
      items: [
        { q: "¿Cuánto tardo en tener el showroom en línea?", a: "Una tarde. Creas la cuenta, subes tu logo, publicas el primer vehículo y ya puedes compartir el enlace. No hay instalación ni configuración técnica." },
        { q: "¿Necesito comprar un dominio?", a: "No. Tu showroom vive en una dirección propia dentro de ZEVROA desde el primer día. Si más adelante quieres usar tu propio dominio, lo conectas desde el panel." },
        { q: "¿Me piden tarjeta para la prueba?", a: "No. Los 14 días de prueba no piden tarjeta. Solo eliges plan cuando decidas seguir." },
        { q: "¿Qué pasa con las fotos y los datos de mis vehículos?", a: "Son tuyos. Puedes exportar tu inventario y tus clientes cuando quieras, y si cancelas no retenemos tu información." },
        { q: "¿Puedo importar el inventario que ya tengo?", a: "Sí. Puedes cargar varios vehículos de una vez desde un Excel y luego ajustar cada ficha desde el panel." },
        { q: "¿Cuánta gente de mi equipo puede entrar?", a: "Puedes crear usuarios con permisos distintos: quien publica el inventario no tiene por qué ver la facturación." },
      ],
    },
    close: {
      kicker: "Tu siguiente vehículo empieza aquí",
      lines: [{ t: "Haz que tu" }, { t: "inventario" }, { t: "se sienta", em: true }, { t: "propio.", em: true }],
      cta: "Crear mi showroom",
    },
    footer: { tagline: "La vitrina digital para concesionarios.", privacy: "Privacidad", terms: "Términos", legalNav: "Enlaces legales" },
    rail: {
      heading: "Un inventario que se recorre.",
      hint: "Desplaza para avanzar",
      items: [
        { name: "Porsche 911 GT3", meta: "2026 · Deportivo", image: "/assets/porsche-911-gt3-rail.webp", alt: "Porsche 911 GT3 en el showroom" },
        { name: "Audi RS e-tron GT", meta: "2025 · Eléctrico", image: "/assets/audi-etron-gt-rail.webp", alt: "Audi RS e-tron GT en el showroom" },
        { name: "BMW M4 Competition", meta: "2024 · Coupé", image: "/assets/bmw-m4-rail.webp", alt: "BMW M4 Competition en el showroom" },
        { name: "Porsche Cayenne Turbo GT", meta: "2026 · SUV", image: "/assets/cayenne-turbo-gt.jpg", alt: "Porsche Cayenne Turbo GT en el showroom" },
        { name: "Mercedes-AMG GT 63", meta: "2025 · Gran turismo", image: "/assets/amg-gt.jpg", alt: "Mercedes-AMG GT 63 en el showroom" },
        { name: "Porsche Macan GTS", meta: "2026 · SUV", image: "/assets/macan-gts-rail.webp", alt: "Porsche Macan GTS en el showroom" },
      ],
    },
    marqueeBrands: ["Porsche", "BMW", "Mercedes-AMG", "Audi", "Land Rover", "Lexus", "Jaguar", "Alfa Romeo", "Bentley", "Ferrari"],
    marqueeLabel: "Marcas con inventario",
    navAria: "Navegación de ZEVROA",
    langAria: "Idioma",
  },
  en: {
    label: "English",
    nav: { experience: "The experience", platform: "The platform", how: "How it works", demo: "See demo", login: "Sign in", cta: "Create showroom" },
    hero: {
      kicker: "Software for dealerships that sell with context",
      lines: [{ t: "Your inventory" }, { t: "sells before", em: true }, { t: "you speak." }],
      body: "Inventory, leads, appointments, and quotes in one experience. Your team knows what each buyer saw and what happens next.",
      primary: "Create my showroom",
      secondary: "Explore a demo",
      metaLeft: "ZEVROA / 2026",
      metaRight: "Inventory · customers · appointments",
      objectLabel: "ZEVROA editorial 3D object",
    },
    proof: {
      kicker: "The platform",
      lines: [{ t: "Inventory, leads," }, { t: "appointments, showroom." }, { t: "All connected." }],
      body: "Publish each vehicle once, reply with the right context, and turn intent into a clear next action.",
      action: "See the platform in action",
      overlayTag: "01 / OPERATIONS",
      overlayLines: [{ t: "One screen" }, { t: "to move forward.", em: true }],
      overlayMeta: "Inventory · CRM · appointments · quotes",
      imageAlt: "ZEVROA panel showing the dealership inventory",
    },
    platform: {
      kicker: "What used to be scattered",
      lines: [{ t: "One operation" }, { t: "that moves" }, { t: "as one." }],
      body: "ZEVROA connects the storefront your buyers see with the tools your team uses to sell.",
      action: "Explore the full flow",
      items: [
        { index: "01", title: "Inventory", body: "Specs, photography, video, and 3D ready to publish." },
        { index: "02", title: "Customers", body: "Every lead arrives with vehicle, channel, and next action." },
        { index: "03", title: "Appointments", body: "Schedule and confirm visits without losing the thread." },
        { index: "04", title: "Quotes", body: "Share a clear proposal and receive the decision." },
      ],
    },
    chapters: [
      {
        kicker: "01 · Publish",
        lines: [{ t: "Your inventory," }, { t: "presented" }, { t: "as it deserves." }],
        body: "Every vehicle ships with full specs, ordered photography, and a preview you approve before any customer sees it.",
        mediaAlt: "Vehicle published in a ZEVROA showroom",
        card: { tag: "Inventory", status: "Published", title: "Porsche Taycan Turbo S", meta: "Full specs · showroom ready" },
      },
      {
        kicker: "02 · Respond",
        lines: [{ t: "Every conversation" }, { t: "arrives with" }, { t: "its context." }],
        body: "You know which vehicle they viewed, what they asked, and who is handling it. Your team replies without rebuilding the story each time.",
        steps: [
          { index: "01 · Signal", title: "Buyers leave clues.", body: "They open a listing, save a model, request a quote. All of it is recorded." },
          { index: "02 · Lead", title: "María wants to see it.", quote: "“Can I book a visit this week?”", meta: "Porsche Taycan Turbo S · 4 min ago" },
          { index: "03 · Reply", title: "Your team answers with everything at hand.", body: "History, vehicle, and next action on the same screen." },
        ],
      },
      {
        kicker: "03 · Close",
        lines: [{ t: "From intent" }, { t: "to a booked visit." }],
        body: "Schedule, quote, and follow through until the customer decides. No loose spreadsheets, no lost conversations.",
        action: "Open example showroom",
        appointment: { tag: "Appointment confirmed", status: "Today", time: "4:30 PM", meta: "Showroom visit · Porsche Cayenne Turbo GT" },
        list: [
          { title: "Schedule", body: "The customer picks a time and your team confirms it in one tap." },
          { title: "Quote", body: "Generate a proposal with pricing, plan, and terms ready to share." },
          { title: "Follow up", body: "Every opportunity moves forward with reminders until it closes." },
        ],
      },
    ],
    pains: {
      kicker: "The day to day",
      heading: "Does this sound familiar?",
      body: "It is not for lack of effort. Inventory, messages and the calendar simply live in different places.",
      items: [
        { before: "You post the same car five times", after: "You load it once and it shows up in your showroom, the listing and the flyer." },
        { before: "You chase a customer on WhatsApp without knowing what they looked at", after: "The lead arrives with the vehicle, the channel and the previous conversation." },
        { before: "You write visits down in a notebook or a chat", after: "The customer picks a time and the appointment lands confirmed in the calendar." },
        { before: "You build every quote by hand", after: "You generate the proposal with price and terms and share it as a link." },
      ],
    },
    compare: {
      kicker: "The difference",
      heading: "The same work, with and without ZEVROA.",
      manual: "By hand",
      withUs: "With ZEVROA",
      rows: [
        { label: "Publishing a vehicle", manual: "Photos over WhatsApp, the same text retyped on every portal", withUs: "One listing that feeds showroom, poster and social" },
        { label: "Answering a lead", manual: "Asking again which vehicle they were interested in", withUs: "History and vehicle on the same screen" },
        { label: "Booking a visit", manual: "Messages back and forth until a time sticks", withUs: "The customer books against your real hours" },
        { label: "Knowing what moved", manual: "Memory and a spreadsheet", withUs: "Reports on inventory, leads and closings" },
        { label: "Having your own site", manual: "Budget, a designer and months", withUs: "Showroom online the same afternoon" },
      ],
    },
    demo: {
      kicker: "Talk to someone",
      heading: "Would you rather we showed you?",
      body: "Leave us your details and we will write within one business day to set up a demo on your own inventory.",
      fields: { name: "Your name", email: "Email", phone: "Phone or WhatsApp", dealership: "Dealership name", size: "How many vehicles do you handle?" },
      sizes: ["Fewer than 20", "20 to 50", "50 to 150", "More than 150"],
      consent: "I agree that ZEVROA may use these details to contact me about the demo.",
      submit: "Request a demo",
      sending: "Sending…",
      success: "Got it. We will write within one business day.",
      error: "It could not be sent. Try again or reach us another way.",
      alt: "Rather try it yourself? Create your showroom and look inside the panel.",
    },
    voices: { kicker: "Dealerships", heading: "What the people already using it say." },
    integrations: {
      kicker: "Connections",
      heading: "Connected to what you already use.",
      body: "No need to migrate how you work. ZEVROA plugs into the tools you already sell with.",
      items: [
        { name: "WhatsApp", detail: "Share listings and answer leads on the channel your customers already use." },
        { name: "Google Calendar", detail: "Confirmed appointments sync with the team calendar." },
        { name: "Instagram and Facebook", detail: "Generate each vehicle's post, ready to publish." },
        { name: "Stripe", detail: "Charge the subscription with checkout and automatic invoicing." },
        { name: "Email", detail: "Lead, appointment and quote alerts to your team inbox." },
        { name: "Spreadsheets", detail: "Upload your whole inventory at once from a spreadsheet." },
        { name: "Your domain", detail: "Connect your own web address whenever you want, or use the included one." },
        { name: "Google and search", detail: "Every listing ships with its SEO, sitemap and structured data." },
      ],
    },
    pricing: {
      kicker: "Plans",
      heading: "You know what you pay before you talk to us.",
      body: "No setup fee, no lock-in, and a 14-day trial. Switch plans from the panel whenever your inventory grows.",
      note: "Prices in USD per month, taxes not included. Every plan includes showroom, inventory, customers and appointment booking.",
      cta: "Start the trial",
      perMonth: "/ mo",
      plans: [
        { code: "starter", name: "Starter", price: "99", limit: "Up to 40 vehicles", body: "For a dealership opening its digital storefront.", features: ["Showroom with your brand", "Inventory and customers", "Appointment booking"] },
        { code: "growth", name: "Growth", price: "249", limit: "Up to 150 vehicles", featured: true, body: "For a sales team already living off leads.", features: ["Everything in Starter", "Social media posts", "Quotes and reports"] },
        { code: "scale", name: "Scale", price: "499", limit: "Unlimited inventory", body: "For operations with several locations and users.", features: ["Everything in Growth", "No vehicle limit", "Priority support"] },
      ],
    },
    faq: {
      kicker: "Before you start",
      heading: "The questions we always get.",
      items: [
        { q: "How long until my showroom is live?", a: "One afternoon. Create the account, upload your logo, publish the first vehicle and share the link. No installation, no technical setup." },
        { q: "Do I need to buy a domain?", a: "No. Your showroom lives on its own address inside ZEVROA from day one. If you later want your own domain, you connect it from the panel." },
        { q: "Do you ask for a card for the trial?", a: "No. The 14-day trial needs no card. You only pick a plan when you decide to continue." },
        { q: "What happens to my vehicle photos and data?", a: "They are yours. You can export your inventory and customers whenever you want, and if you cancel we do not hold on to your information." },
        { q: "Can I import the inventory I already have?", a: "Yes. You can upload several vehicles at once from a spreadsheet and then adjust each listing from the panel." },
        { q: "How many people from my team can log in?", a: "You can create users with different permissions: whoever publishes inventory does not need to see billing." },
      ],
    },
    close: {
      kicker: "Your next vehicle starts here",
      lines: [{ t: "Make your" }, { t: "inventory" }, { t: "feel like", em: true }, { t: "your own.", em: true }],
      cta: "Create my showroom",
    },
    footer: { tagline: "The digital storefront for dealerships.", privacy: "Privacy", terms: "Terms", legalNav: "Legal links" },
    rail: {
      heading: "An inventory you travel through.",
      hint: "Scroll to advance",
      items: [
        { name: "Porsche 911 GT3", meta: "2026 · Sports", image: "/assets/porsche-911-gt3-rail.webp", alt: "Porsche 911 GT3 in the showroom" },
        { name: "Audi RS e-tron GT", meta: "2025 · Electric", image: "/assets/audi-etron-gt-rail.webp", alt: "Audi RS e-tron GT in the showroom" },
        { name: "BMW M4 Competition", meta: "2024 · Coupe", image: "/assets/bmw-m4-rail.webp", alt: "BMW M4 Competition in the showroom" },
        { name: "Porsche Cayenne Turbo GT", meta: "2026 · SUV", image: "/assets/cayenne-turbo-gt.jpg", alt: "Porsche Cayenne Turbo GT in the showroom" },
        { name: "Mercedes-AMG GT 63", meta: "2025 · Grand tourer", image: "/assets/amg-gt.jpg", alt: "Mercedes-AMG GT 63 in the showroom" },
        { name: "Porsche Macan GTS", meta: "2026 · SUV", image: "/assets/macan-gts-rail.webp", alt: "Porsche Macan GTS in the showroom" },
      ],
    },
    marqueeBrands: ["Porsche", "BMW", "Mercedes-AMG", "Audi", "Land Rover", "Lexus", "Jaguar", "Alfa Romeo", "Bentley", "Ferrari"],
    marqueeLabel: "Brands in inventory",
    navAria: "ZEVROA navigation",
    langAria: "Language",
  },
};
