// Abbreviated AUTHENTIQ catalog — real photos from /assets
const CATALOG = [
  {
    id: "porsche-911-gt3",
    brand: "Porsche",
    model: "911 GT3",
    year: 2026,
    kind: "new",
    tag: "Nuevo",
    price: 189500,
    tagline: "Purista. Analógico. Definitivo.",
    image: "../../assets/porsche-911-gt3.jpg",
    images: [
      "../../assets/porsche-911-gt3.jpg",
      "../../assets/porsche-911-gt3-alt.jpg",
      "../../assets/porsche-911-three-quarter.jpg",
      "../../assets/porsche-interior.jpg",
    ],
    specs: {
      "Motor": "4.0L H6",
      "Potencia": "502 hp",
      "Par motor": "470 Nm",
      "0-100 km/h": "3.2s",
      "Vel. máxima": "318 km/h",
      "Transmisión": "7-Speed PDK",
      "Tracción": "RWD",
      "Kilometraje": "0 km",
    },
    colors: [
      { name: "Chalk", hex: "#e5e2d8" },
      { name: "Negro Volcánico", hex: "#0a0a0a" },
      { name: "Gris Ágata", hex: "#5a5852" },
      { name: "Champagne", hex: "#c8a24b" },
      { name: "Rojo Guardia", hex: "#a63325" },
    ],
    stock: 2,
    views: 847,
  },
  {
    id: "porsche-cayenne",
    brand: "Porsche",
    model: "Cayenne Turbo GT",
    year: 2026,
    kind: "new",
    tag: "Nuevo",
    price: 195700,
    tagline: "Fuerza sin compromiso.",
    image: "../../assets/cayenne-turbo-gt.jpg",
    images: ["../../assets/cayenne-turbo-gt.jpg", "../../assets/cayenne-turbo-gt-2.jpg"],
    specs: {
      "Motor": "4.0L V8 Twin-Turbo",
      "Potencia": "631 hp",
      "0-100 km/h": "3.3s",
      "Vel. máxima": "300 km/h",
      "Transmisión": "8-Speed Tiptronic",
      "Tracción": "AWD",
      "Kilometraje": "0 km",
    },
    colors: [
      { name: "Carrara White", hex: "#f0eee8" },
      { name: "Volcanic Black", hex: "#1a1917" },
      { name: "Gentian Blue", hex: "#1e3a5f" },
    ],
    stock: 1,
    views: 512,
  },
  {
    id: "porsche-taycan",
    brand: "Porsche",
    model: "Taycan Turbo S",
    year: 2025,
    kind: "used",
    tag: "Certificado",
    price: 142000,
    tagline: "El futuro, en modo silencioso.",
    image: "../../assets/taycan-turbo-s.jpg",
    images: ["../../assets/taycan-turbo-s.jpg", "../../assets/taycan-turbo-s-2.jpg"],
    specs: {
      "Motor": "Eléctrico bi-motor",
      "Potencia": "761 hp",
      "0-100 km/h": "2.8s",
      "Autonomía": "467 km",
      "Transmisión": "2-Speed",
      "Tracción": "AWD",
      "Kilometraje": "12,400 km",
    },
    colors: [
      { name: "Frozen Blue", hex: "#c9d4dc" },
      { name: "Black", hex: "#0a0a0a" },
    ],
    stock: 1,
    views: 634,
  },
  {
    id: "bmw-m4",
    brand: "BMW",
    model: "M4 Competition",
    year: 2025,
    kind: "used",
    tag: "Certificado",
    price: 98500,
    tagline: "Adrenalina bavara.",
    image: "../../assets/bmw-m4.jpg",
    images: ["../../assets/bmw-m4.jpg", "../../assets/bmw-m4-2.jpg"],
    specs: {
      "Motor": "3.0L I6 Twin-Turbo",
      "Potencia": "503 hp",
      "0-100 km/h": "3.5s",
      "Vel. máxima": "290 km/h",
      "Transmisión": "8-Speed M Steptronic",
      "Tracción": "RWD",
      "Kilometraje": "8,900 km",
    },
    colors: [
      { name: "Sao Paulo Yellow", hex: "#e8c246" },
      { name: "Alpine White", hex: "#f0eee8" },
    ],
    stock: 1,
    views: 412,
  },
  {
    id: "amg-gt",
    brand: "Mercedes-AMG",
    model: "GT 63 S",
    year: 2026,
    kind: "new",
    tag: "Nuevo",
    price: 178000,
    tagline: "Escultura en cuatro tiempos.",
    image: "../../assets/amg-gt.jpg",
    images: ["../../assets/amg-gt.jpg", "../../assets/amg-gt-2.jpg"],
    specs: {
      "Motor": "4.0L V8 Biturbo",
      "Potencia": "630 hp",
      "0-100 km/h": "3.2s",
      "Vel. máxima": "315 km/h",
      "Transmisión": "9-Speed AMG",
      "Tracción": "AWD",
      "Kilometraje": "0 km",
    },
    colors: [
      { name: "Selenite Grey", hex: "#525050" },
      { name: "Obsidian Black", hex: "#0d0c0a" },
    ],
    stock: 2,
    views: 378,
  },
  {
    id: "audi-etron-gt",
    brand: "Audi",
    model: "e-tron GT",
    year: 2026,
    kind: "new",
    tag: "Nuevo",
    price: 132000,
    tagline: "Silencio eléctrico, presencia atómica.",
    image: "../../assets/audi-etron-gt.jpg",
    images: ["../../assets/audi-etron-gt.jpg"],
    specs: {
      "Motor": "Eléctrico bi-motor",
      "Potencia": "637 hp",
      "0-100 km/h": "3.1s",
      "Autonomía": "488 km",
      "Transmisión": "2-Speed",
      "Tracción": "quattro",
      "Kilometraje": "0 km",
    },
    colors: [
      { name: "Kemora Grey", hex: "#4b4a48" },
      { name: "Suzuka Grey", hex: "#a5a5a2" },
    ],
    stock: 1,
    views: 289,
  },
];

const REVIEWS = [
  {
    id: "r1",
    stars: 5,
    text: "La compra fue tan editorial como el auto. Cero fricción, cero adornos. Todo verificado antes de la entrega.",
    vehicle: "Porsche 911 GT3 · 2026",
    author: "Sofía R.",
    role: "Comprador · CDMX",
    avatar: "../../assets/reviewer-1.jpg",
  },
  {
    id: "r2",
    stars: 5,
    text: "Agenté un test drive a las 22:00 y a las 09:15 del día siguiente ya estaba conduciendo. El proceso respeta tu tiempo.",
    vehicle: "Porsche Cayenne Turbo GT · 2026",
    author: "Andrés M.",
    role: "Comprador · Monterrey",
    avatar: "../../assets/reviewer-2.jpg",
  },
  {
    id: "r3",
    stars: 5,
    text: "El comparador lado a lado es honesto. Muestra la información como es, sin favorecer un modelo sobre otro.",
    vehicle: "Taycan Turbo S · 2025",
    author: "Lucía P.",
    role: "Comprador · Guadalajara",
    avatar: "../../assets/reviewer-3.jpg",
  },
];

Object.assign(window, { CATALOG, REVIEWS });
